### ISSUE TITLE
pikepdf's extension library failed to import

### ISSUE THREAD

**Issue by nothing2obvi** [linuxserver/docker-paperless-ng#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Documents should get "consumed" as expected

## Current Behavior

Paperless-ng displays that it is currently processing all those files (if I put in 28, it counts 28), but then nothing appears in my documents.

## Steps to Reproduce

1. Put PDFs in /data/consume
2. Restart Paperless-ng. Paperless-ng says it is processing the PDFs.
3. No documents appear. Document count is 0.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "2.1"
services:
  davos:
    image: lscr.io/linuxserver/paperless-ng
    container_name: paperless-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /Users/username/Docker/paperless-ng/config:/config
      - /Users/username/Docker/paperless-ng/data/media:/data/media
      - /Users/username/Docker/paperless-ng/data/consume:/data/consume
      - /Users/Shared/Documents/Papers-OUT:/data/export
    ports:
      - 8100:8000
    restart: unless-stopped
networks:
  default:
    external: true
    name: lsio
```

## Docker logs

```
today at 7:12:39 PM02:12:39 [Q] INFO recycled worker Process-1:12
today at 7:12:39 PM02:12:39 [Q] INFO Process-1:16 ready for work at 520
today at 7:12:39 PM02:12:39 [Q] INFO Process-1:16 processing [name-of-the-document.pdf]
today at 7:12:39 PM[2022-04-28 02:12:39,631] [INFO] [paperless.consumer] Consuming name-of-the-document.pdf
today at 7:12:39 PM02:12:39 [Q] INFO Process-1:15 stopped doing work
today at 7:12:40 PM02:12:40 [Q] INFO recycled worker Process-1:15
today at 7:12:40 PM02:12:40 [Q] INFO Process-1:17 ready for work at 528
today at 7:12:40 PM02:12:40 [Q] INFO Process-1:17 processing [name-of-the-2nd-document.pdf]
today at 7:12:40 PM02:12:40 [Q] ERROR Failed [name-of-the-3rd-document] - pikepdf's extension library failed to import : Traceback (most recent call last):
today at 7:12:40 PM  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 13, in <module>
today at 7:12:40 PM    from . import _qpdf
today at 7:12:40 PMImportError: /usr/local/lib/python3.8/dist-packages/pikepdf/_qpdf.cpython-38-aarch64-linux-gnu.so: undefined symbol: _ZN20QPDFPageObjectHelper16placeFormXObjectE16QPDFObjectHandleRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_9RectangleEbbb
today at 7:12:40 PM
today at 7:12:40 PMThe above exception was the direct cause of the following exception:
today at 7:12:40 PM
today at 7:12:40 PMTraceback (most recent call last):
today at 7:12:40 PM  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 432, in worker
today at 7:12:40 PM    res = f(*task["args"], **task["kwargs"])
today at 7:12:40 PM  File "/app/paperless/src/documents/tasks.py", line 74, in consume_file
today at 7:12:40 PM    document = Consumer().try_consume_file(
today at 7:12:40 PM  File "/app/paperless/src/documents/consumer.py", line 248, in try_consume_file
today at 7:12:40 PM    document_parser.parse(self.path, mime_type, self.filename)
today at 7:12:40 PM  File "/app/paperless/src/paperless_tesseract/parsers.py", line 230, in parse
today at 7:12:40 PM    import ocrmypdf
today at 7:12:40 PM  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/__init__.py", line 10, in <module>
today at 7:12:40 PM    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
today at 7:12:40 PM  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/helpers.py", line 22, in <module>
today at 7:12:40 PM    import pikepdf
today at 7:12:40 PM  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 16, in <module>
today at 7:12:40 PM    raise ImportError(_msg) from _e
today at 7:12:40 PMImportError: pikepdf's extension library failed to import
```
